name: raspundel_updater
description: A GUI application to update Raspunde Istetel pens with latest .bnl files.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  path: ^1.8.3
  html: ^0.15.4
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  flutter_local_notifications: ^15.1.1
  percent_indicator: ^4.2.3
  lottie: ^2.6.0
  usb_serial: ^0.4.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true